sudo: false
language: ruby
install:
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - if [ -n "$RUBOCOP" ]; then gem install rubocop -v 0.52.0 && rubocop; fi
  - ../mspec/bin/mspec $MSPEC_OPTS
matrix:
  include:
    - rvm: 2.5.0
      env: MSPEC_OPTS="-R2 -ff"
    - rvm: 2.2.9
    - rvm: 2.3.6
    - rvm: 2.4.3
    - rvm: 2.5.0
      env: CHECK_LEAKS=true RUBOCOP=true
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
branches:
  only:
    - master
    - /^try/
notifications:
  email:
    on_success: change
    on_failure: change
