---
version: "{build}"
clone_depth: 100
init:
  # To avoid duplicated executables in PATH, see https://github.com/ruby/spec/pull/468
  - set PATH=C:\Ruby%ruby_version%\bin;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;C:\Program Files\Git\cmd;C:\Windows\system32;C:\Program Files;C:\Windows

environment:
  matrix:
    - ruby_version: 24-x64
    - ruby_version: 25-x64
install:
  - git clone https://github.com/ruby/mspec.git ../mspec
build: off
test_script:
  - SET CHECK_LEAKS=true
  - ../mspec/bin/mspec -rdevkit -ff
on_finish:
  - ruby -v
branches:
  only:
    - master
    - /^try/
